spring:
  redis:
    host: 185.200.34.214
    port: 16633
    timeout: 10000ms
    jedis:
      pool:
        max-idle: 20
        min-idle: 5
        max-active: 20
        max-wait: 1000ms
    password: "FW@18.06#pN2UnG"

logging:
  level:
    root: error
